import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import Form from '../components/form'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='oval' >
        <Image src='/images/icon-star.svg'className='w-[14px] h-[14px] ' width={'14px'} height={'14px'}/>
      </div>
      <h1>How did we do?</h1>
      <p>
        Please let us know how we did with your support request. 
        All feedback is appreciated to help us improve our offering!
      </p>
      <Form />

    </Layout>
  )
}
