import Head from 'next/head'
import Layout from '../components/layout'
import Form from '../components/form'
import ThankYou from '../components/thank-you'
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function ThankYouPage() {
    // non-JS submission
    const router = useRouter()
    const {rating} = router.query

    // JS-submission
    const [formRating, setFormRating] = useState()

  return (
    <Layout>
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {rating && <ThankYou formRating={rating} />}

    </Layout>
  )
}