import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import Form from '../components/form'

export default function Home() {
  return (
    <Layout>
        <Head>
            <title>Frontend Mentor | Interactive rating component</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Image src={'/images/illustration-thank-you.svg'} width={'143px'} height={'96px'} alt='thank you'/>
        <span className='rounded-[22.5px] bg-dark-blue text-orange mt-6 mb-3 px-3 py-1 font-normal text-sm leading-[22px]'>
            FORM_RESPONSE_HERE
        </span>
        <h1>Thank you!</h1>
        <p className='text-center'>
            We appreciate you taking the time to give a rating. If you ever need more support, don’t hesitate to get in touch!
        </p>
    </Layout>
  )
}
